// COPYRIGHT (C) HARRY CLARK 2025
// SMALL PACKED STRUCT UTILITY

// THE FOLLOWING FILE WAS A LITTLE SOMETHING I WANTED TO MAKE AS PART OF MY CONTINIOUS
// LEARNING AND UNDERSTANDING OF THE INNER WORKINGS OF THE C LANGUAGE

// MOST NOTABLY, I HAD OFTEN NOTICED THAT PROJECTS INCLUDED SOME FORM OF DOCUMENTATION
// WHICH SERVED TO SHOWCASE HOW FIELDS IN A STRUCT ARE PADDED IN RELATION TO THEIR SIZE

// THEREFORE, I WANTED TO MAKE SOMETHING THAT SERVES TO PROVIDE THAT UNDERSTANDING
// AND TO VALLIDATE THE FUNCTIONALITY ENCOMPASSING SUCH

// NESTED INCLUDES

#include "offset.h"

size_t SIZE = 0;
const char* MEM_MSG[] = 
{
    "MEM ACCESS",
    "PADDING DETECTED",
    "OFFSET TRACKING",
    "FINAL SIZE"
};

int main(void) 
{
    PRINT_OFFSET(MY_STRUCT, VAR_1);
    PRINT_OFFSET(MY_STRUCT, VAR_2);
    PRINT_OFFSET(MY_STRUCT, VAR_3);
    PRINT_OFFSET(MY_STRUCT, VAR_4);
    PRINT_SIZE(MY_STRUCT);
    
    return 0;
}
